url: http://h2012.fi
cdn: http://h2012.fi
secure_cdn: https://cdn.example.com.invalid

title: Vihreät Hankasalmella
description: Vihreiden kunnallisvaalikampanja Hankasalmella
language: fi
theme: default

style_version: dev
scripts_version: dev

author: Ville Korhonen
email: ville.korhonen@vihreat.fi

markdown: rdiscount
pygments: true
exclude:
    - README.md
    - requirements.txt

permalink: pretty
